// <auto-generated />
using AspKutuphane.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspKutuphane.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260506115410_AddDepartmentToStudent")]
    partial class AddDepartmentToStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AspKutuphane.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "1.jpg.webp",
                            IsBorrowed = false,
                            Title = "Bozkırın Oğlu"
                        },
                        new
                        {
                            Id = 2,
                            Image = "2.jpg.webp",
                            IsBorrowed = false,
                            Title = "Bozkırın İlk İmparatorluğu Hunlar"
                        },
                        new
                        {
                            Id = 3,
                            Image = "3.jpg.webp",
                            IsBorrowed = false,
                            Title = "Bozkırın Kağanlıkları"
                        },
                        new
                        {
                            Id = 4,
                            Image = "4.jpg.webp",
                            IsBorrowed = false,
                            Title = "Gök Tengrinin Çocukları"
                        },
                        new
                        {
                            Id = 5,
                            Image = "5.jpg.webp",
                            IsBorrowed = false,
                            Title = "Eski Türk Tarihi"
                        },
                        new
                        {
                            Id = 6,
                            Image = "6.jpg.webp",
                            IsBorrowed = false,
                            Title = "Gökbörünün İzinde"
                        },
                        new
                        {
                            Id = 7,
                            Image = "7.jpg.webp",
                            IsBorrowed = false,
                            Title = "Eski Türk Boyları"
                        },
                        new
                        {
                            Id = 8,
                            Image = "8.jpg.webp",
                            IsBorrowed = false,
                            Title = "Tarih Boyunca Türk Kadını"
                        },
                        new
                        {
                            Id = 9,
                            Image = "9.jpg.webp",
                            IsBorrowed = false,
                            Title = "İlk Türkler"
                        },
                        new
                        {
                            Id = 10,
                            Image = "10.jpg.webp",
                            IsBorrowed = false,
                            Title = "Kadim Türkler"
                        },
                        new
                        {
                            Id = 11,
                            Image = "11.jpg.webp",
                            IsBorrowed = false,
                            Title = "İslamiyet Öncesi Türkler"
                        },
                        new
                        {
                            Id = 12,
                            Image = "12.jpg.webp",
                            IsBorrowed = false,
                            Title = "Milli Mücadele Tarihi"
                        },
                        new
                        {
                            Id = 13,
                            Image = "13.jpg.webp",
                            IsBorrowed = false,
                            Title = "Osmanlı Ve Avrupa"
                        },
                        new
                        {
                            Id = 14,
                            Image = "14.jpg.webp",
                            IsBorrowed = false,
                            Title = "Devlet-i Alliyye"
                        },
                        new
                        {
                            Id = 15,
                            Image = "15.jpg.webp",
                            IsBorrowed = false,
                            Title = "Osmanlı Tarihinde Efsaneler ve Gerçekler"
                        },
                        new
                        {
                            Id = 16,
                            Image = "16.jpg.webp",
                            IsBorrowed = false,
                            Title = "İmparatorluktan Cumhuriyete"
                        },
                        new
                        {
                            Id = 17,
                            Image = "17.jpg.webp",
                            IsBorrowed = false,
                            Title = "Kısa Osmanlı Tarihi"
                        },
                        new
                        {
                            Id = 18,
                            Image = "18.jpg.webp",
                            IsBorrowed = false,
                            Title = "Fatih Sultan Mehmet Han"
                        },
                        new
                        {
                            Id = 19,
                            Image = "19.jpg.webp",
                            IsBorrowed = false,
                            Title = "Osmanlı İmparatorluğu Klasik Çağ"
                        },
                        new
                        {
                            Id = 20,
                            Image = "20.jpg.webp",
                            IsBorrowed = false,
                            Title = "Cumhiriyetin İlk Yüzyılı"
                        },
                        new
                        {
                            Id = 21,
                            Image = "21.jpg.webp",
                            IsBorrowed = false,
                            Title = "İmparatorluğun En Uzun Yüzyılı"
                        },
                        new
                        {
                            Id = 22,
                            Image = "22.jpg.webp",
                            IsBorrowed = false,
                            Title = "Türkiyenin Yakın Tarihi"
                        },
                        new
                        {
                            Id = 23,
                            Image = "23.jpg.webp",
                            IsBorrowed = false,
                            Title = "Türklerin Tarihi"
                        },
                        new
                        {
                            Id = 24,
                            Image = "24.jpg.webp",
                            IsBorrowed = false,
                            Title = "Kısa Osmanlı Tarihi"
                        },
                        new
                        {
                            Id = 25,
                            Image = "25.jpg.webp",
                            IsBorrowed = false,
                            Title = "Yakın Tarihin Gerçekleri"
                        },
                        new
                        {
                            Id = 26,
                            Image = "26.jpg.webp",
                            IsBorrowed = false,
                            Title = "İlber Ortaylı Seyahatnamesi"
                        },
                        new
                        {
                            Id = 27,
                            Image = "27.jpg.webp",
                            IsBorrowed = false,
                            Title = "Kurtuluş Cumhuriyete Giden Yol"
                        },
                        new
                        {
                            Id = 28,
                            Image = "28.jpg.webp",
                            IsBorrowed = false,
                            Title = "Zaman Kaybolmaz"
                        },
                        new
                        {
                            Id = 29,
                            Image = "29.jpg.webp",
                            IsBorrowed = false,
                            Title = "Gel Dünyayı Keşfetelim"
                        },
                        new
                        {
                            Id = 30,
                            Image = "30.jpg.webp",
                            IsBorrowed = false,
                            Title = "Gazi Mustafa Kemal Atatürk"
                        },
                        new
                        {
                            Id = 31,
                            Image = "31.jpg.webp",
                            IsBorrowed = false,
                            Title = "Fatih Sultan Mehmet Han"
                        },
                        new
                        {
                            Id = 32,
                            Image = "32.jpg.webp",
                            IsBorrowed = false,
                            Title = "Bir Ömür Nasıl Yaşanır"
                        });
                });

            modelBuilder.Entity("AspKutuphane.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspKutuphane.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspKutuphane.Models.Book", b =>
                {
                    b.HasOne("AspKutuphane.Models.Student", "Student")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AspKutuphane.Models.Student", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
